### PR TITLE
Pul Request for #3: Add function for distributional TE

### PR DESCRIPTION
**Pull request by mcaceresb**

### CODE REVIEW

**Comment by mcaceresb** [comment]
@jonathandroth The minimum wage data in this repo is from Callaway and Sant'Anna (2021), but in the paper you use  Cengiz et al. (2019). The latter is also in the README draft I have. Which should I be using? (And if the latter, I'm not sure  which it is. Should I just sift through the replication archive?)

**Comment by jonathandroth** [comment]
Hmm, that's odd. @pedrohcgs, did you try to swap out the data here? I would be inclined to stick to something close to what we had in our ECMA paper unless there's a compelling reason otherwise?

**Comment by mcaceresb** [comment]
@jonathandroth @pedrohcgs So which dataset should I use? To clarify, at the moment the CS data is being used in the unit tests but it's not in the README. The RADME uses the Cengiz et al. data, which is not currently included in this repo. LMK.

**Comment by pedrohcgs** [comment]
Ideally, I think we should use Cengiz et al data to illustrate 2 periods
and then use CS for multiple periods.

But I think Cengiz et al need formatting to fit our code, probably.

What do you think, @jonathandroth <https://github.com/jonathandroth>?

**Comment by jonathandroth** [comment]
It's been a long time, but I think Andres created a reformatted version of the Cengiz et al data here: https://github.com/amenabrown/didFF

Unless there's something I'm missing, I'd be inclined to just use that one?

**Comment by mcaceresb** [comment]
- I got the data from Andres, but in the end I don't think I needed that because I found the data on the ECMA replication package online.

- I am confused about how to use Cengiz et al. with the way `didFF` is set up. In the paper you have the fraction of the population employed at each wage bin. However, `didFF` assumes everyone is in the data, so if I weight by number employed I don't get the same because that doesn't add up to the population (the implied density is inflated by 1/fraction employed overall). So how would I do Figure 2 with `didFF`?

**Comment by jonathandroth** [comment]
The idea is that if we had micro-data with each person's wage, and people
not working had wage set to 0, then this would exactly match the set-up in
the ECMA paper. We don't actually have micro-data, we have aggregates. But
if we treat each wage-bin by state as an observation and weight them, it
should be the same. Andres took the data that we had in the ECMA
replication package and reformatted it so that each row is a
state-year-wage bin, and there is a zero wage bin. He was able to almost
exactly match the results in the ECMA paper (there was a very slight
difference owing to the fact that in the paper, we did include a moment
inequality for the zero wage bin). Does that make sense?

**Comment by mcaceresb** [comment]
@jonathandroth Yes a zero wage bin should work. Thanks for clarifying!

**Comment by jonathandroth** [comment]
Sure, thanks for your help!

IIRC, there was some funkinesss related to the fact that for Washington DC,
the working population is larger than the native population, so the implied
employment in the zero wage bin was negative. I think we "fixed" this by
setting it to zero, but it's been a long time so i'm hazy on the details.

J

**Comment by jonathandroth** [comment]
Thanks Mauricio! Regarding the discrepancy in pvals, I believe that Andres's code and our ECMA paper used a bootstrap for the variance covariance matrix, but to speed things up, @pedrohcgs implemented an analytical version of the variance calculation here (is that right, Pedro?) My guess is the change from p=0.29 to p=0.33 is the result of the change in variance, although it'd be useful to verify. 

I'll look at the README a little later

**Comment by mcaceresb** [comment]
@jonathandroth On the p-value, I think it's a combination of that and missing values in the DF. There's a slight discrepancy in the number of rows, as I mentioned, and there's also a slight discrepancy in the estimates. That plus the slightly different variance from the bootstrap make it so the estimated critical value is off in a way that translates to 5pp for the p-value. The same issue happens with the other p-value, but there it was less clear because the p-value is so small.

LMK when you've had a chance to have a look at the README and I'll figure out how to merge. (It seems I accidentally closed this PR.)

**Comment by mcaceresb** [comment]
@jonathandroth Just checking in!

**Comment by mcaceresb** [comment]
Continued in #5.

**Pull request closed without merging**
